using System;
using System.IO;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using UnityEngine;

namespace MobileBridge
{
    /// <summary>
    /// Runtime-only certificate helper: load and check the self-signed certificate
    /// that was previously generated by the Editor-side CertificateGenerator.
    ///
    /// Storage format:
    ///   cert.pem       — X.509 certificate, DER-encoded and base64-wrapped (PEM)
    ///   key-params.xml — RSA private key in XML format (RSACryptoServiceProvider XML)
    ///
    /// Why XML for the key?
    ///   Unity 2022.3 / Mono stubs out most System.Security.Cryptography key-import
    ///   APIs (ImportPkcs8PrivateKey, ImportRSAPrivateKey, etc.) — they throw
    ///   PlatformNotSupportedException at runtime.
    ///   RSACryptoServiceProvider.FromXmlString() is genuinely implemented on Mono
    ///   and is sufficient for our needs.
    ///
    /// NOTE: Certificate *generation* is intentionally absent here.
    ///       Generation requires Editor-only BouncyCastle APIs and must never be
    ///       compiled into the player build. See Editor/CertificateGenerator.cs.
    /// </summary>
    public static class CertificateHelper
    {
        private const string SubDir      = "MobileBridge";
        private const string CertFile    = "cert.pem";
        private const string KeyXmlFile  = "key-params.xml";
        private const int    ValidDays   = 365;

        public static string CertPath =>
            Path.Combine(Application.persistentDataPath, SubDir, CertFile);

        public static string KeyXmlPath =>
            Path.Combine(Application.persistentDataPath, SubDir, KeyXmlFile);

        public static bool CertExists() =>
            File.Exists(CertPath) && File.Exists(KeyXmlPath);

        public static bool NeedsRenewal()
        {
            if (!CertExists()) return true;
            try
            {
                byte[] der = DecodePem(File.ReadAllText(CertPath));
                using var cert = new X509Certificate2(der);
                return cert.NotAfter < DateTime.UtcNow.AddDays(30);
            }
            catch { return true; }
        }

        /// <summary>
        /// Load the certificate from disk and attach the private key.
        /// Returns null if the certificate does not exist or cannot be loaded.
        /// Callers should check CertExists() / NeedsRenewal() beforehand and
        /// prompt the user to (re)generate via the Editor window if null is returned.
        /// </summary>
        public static X509Certificate2 Load()
        {
            if (!CertExists()) return null;
            try
            {
                // ── Load public cert from PEM ─────────────────────────────────
                byte[] certDer = DecodePem(File.ReadAllText(CertPath));
                var cert = new X509Certificate2(certDer);

                // ── Load private key from XML ─────────────────────────────────
                // FromXmlString is genuinely implemented on Mono (unlike
                // ImportPkcs8PrivateKey / ImportRSAPrivateKey which throw
                // PlatformNotSupportedException on Unity's Mono runtime).
                var rsa = new RSACryptoServiceProvider();
                rsa.FromXmlString(File.ReadAllText(KeyXmlPath));

                // ── Combine cert + private key ────────────────────────────────
                // CopyWithPrivateKey is available in .NET Standard 2.1
                // (Unity 2022.3 LTS, apiCompatibility = .NET Standard 2.1).
                return cert.CopyWithPrivateKey(rsa);
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[MobileBridge] CertificateHelper.Load failed: {ex.Message}");
                return null;
            }
        }

        /// <summary>
        /// Returns the machine's LAN IP address.
        /// Enumerates network interfaces first to avoid macOS virtual/test
        /// addresses (e.g. 198.18.x.x). Falls back to UDP connect trick.
        /// </summary>
        public static string GetLocalIPAddress()
        {
            // 1. Prefer private RFC-1918 address from a real NIC
            foreach (var ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                if (ni.OperationalStatus != OperationalStatus.Up) continue;
                if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback) continue;

                foreach (var ua in ni.GetIPProperties().UnicastAddresses)
                {
                    if (ua.Address.AddressFamily != AddressFamily.InterNetwork) continue;
                    if (IPAddress.IsLoopback(ua.Address)) continue;

                    var b = ua.Address.GetAddressBytes();
                    if (b[0] == 10) return ua.Address.ToString();
                    if (b[0] == 172 && b[1] >= 16 && b[1] <= 31) return ua.Address.ToString();
                    if (b[0] == 192 && b[1] == 168) return ua.Address.ToString();
                }
            }

            // 2. UDP-connect fallback (no packets sent)
            try
            {
                using var sock = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, 0);
                sock.Connect("8.8.8.8", 65530);
                return ((IPEndPoint)sock.LocalEndPoint).Address.ToString();
            }
            catch { return null; }
        }

        // ── PEM helpers ────────────────────────────────────────────────────────

        /// <summary>
        /// Decode the first PEM block in <paramref name="pem"/> and return the
        /// raw DER bytes. Throws <see cref="FormatException"/> if no valid block
        /// is found.
        /// </summary>
        public static byte[] DecodePem(string pem)
        {
            const string header = "-----BEGIN ";
            const string footer = "-----END ";

            int start = pem.IndexOf(header, StringComparison.Ordinal);
            if (start < 0) throw new FormatException("No PEM header found.");

            // Find the end of the "-----BEGIN xxx-----" line
            int bodyStart = pem.IndexOf('\n', start);
            if (bodyStart < 0) throw new FormatException("Malformed PEM header.");
            bodyStart++; // skip the newline itself

            int end = pem.IndexOf(footer, bodyStart, StringComparison.Ordinal);
            if (end < 0) throw new FormatException("No PEM footer found.");

            string base64 = pem.Substring(bodyStart, end - bodyStart)
                               .Replace("\r", "").Replace("\n", "");
            return Convert.FromBase64String(base64);
        }
    }
}
